### ISSUE TITLE
Cannot Build on x86_64

### ISSUE THREAD

**Issue by Ardincani** [ReverseApple/RemoveBooksDRM#2]
the error i get with build.sh 

injected.m:152:11: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
    NSLog(baseDirectory);
          ^~~~~~~~~~~~~
injected.m:152:11: note: treat the string as an argument to avoid this
    NSLog(baseDirectory);
          ^
          @"%@", 
injected.m:221:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
^
2 warnings generated.

**Comment by AngeloD2022** [comment]
Hi! Could you specify your CPU?

**Comment by Ardincani** [comment]
Hey. its an i7 - 1068NG7

**Comment by AngeloD2022** [comment]
It looks like you're getting warnings instead of errors. But since you're on an Intel CPU, I'd recommend removing the ` -arch arm64e` flag from build.sh

**Comment by Ardincani** [comment]
this is what it shows now:

injected.m:152:11: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
    NSLog(baseDirectory);
          ^~~~~~~~~~~~~
injected.m:152:11: note: treat the string as an argument to avoid this
    NSLog(baseDirectory);
          ^
          @"%@", 
injected.m:221:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
^
2 warnings generated.
Undefined symbols for architecture x86_64:
  "_NSHomeDirectory", referenced from:
      _try_decrypt_epub in injected-e9f96f.o
      _discoverEPUB in injected-e9f96f.o
  "_NSLog", referenced from:
      _get_sinf in injected-e9f96f.o
      _try_decrypt in injected-e9f96f.o
      _write_file in injected-e9f96f.o
      _write_file in injected-e9f96f.o
      _write_file in injected-e9f96f.o
      _make_base_epub_dir in injected-e9f96f.o
      _try_decrypt_epub in injected-e9f96f.o
      _try_decrypt_epub in injected-e9f96f.o
      _try_decrypt_epub in injected-e9f96f.o
      _try_decrypt_epub in injected-e9f96f.o
      _try_decrypt_epub in injected-e9f96f.o
      _try_decrypt_epub in injected-e9f96f.o
      _try_decrypt_epub in injected-e9f96f.o
      _try_decrypt_epub in injected-e9f96f.o
      ...
  "_OBJC_CLASS_$_NSConstantArray", referenced from:
       in injected-e9f96f.o
       in injected-e9f96f.o
  "_OBJC_CLASS_$_NSData", referenced from:
       in injected-e9f96f.o
  "_OBJC_CLASS_$_NSFileManager", referenced from:
       in injected-e9f96f.o
  "_OBJC_CLASS_$_NSString", referenced from:
       in injected-e9f96f.o
  "___CFConstantStringClassReference", referenced from:
       in injected-e9f96f.o
       in injected-e9f96f.o
       in injected-e9f96f.o
       in injected-e9f96f.o
       in injected-e9f96f.o
       in injected-e9f96f.o
       in injected-e9f96f.o
      ...
  "_objc_alloc", referenced from:
      _get_sinf in injected-e9f96f.o
  "_objc_enumerationMutation", referenced from:
      _try_decrypt_epub in injected-e9f96f.o
  "_objc_getClass", referenced from:
      _try_decrypt in injected-e9f96f.o
  "_objc_msgSend", referenced from:
      _get_sinf in injected-e9f96f.o
      _get_sinf in injected-e9f96f.o
      _get_sinf in injected-e9f96f.o
      _get_sinf in injected-e9f96f.o
      _get_sinf in injected-e9f96f.o
      _get_sinf in injected-e9f96f.o
      _get_sinf in injected-e9f96f.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by AngeloD2022** [comment]
Maybe try adding the `-lobjc` flag to the clang command.

**Comment by Ardincani** [comment]
now it shows this: 

injected.m:152:11: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
    NSLog(baseDirectory);
          ^~~~~~~~~~~~~
injected.m:152:11: note: treat the string as an argument to avoid this
    NSLog(baseDirectory);
          ^
          @"%@", 
injected.m:221:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}
^
2 warnings generated.
 "/Library/Developer/CommandLineTools/usr/bin/ld" -demangle -lto_library /Library/Developer/CommandLineTools/usr/lib/libLTO.dylib -no_deduplicate -dynamic -dylib -arch x86_64 -platform_version macos 14.0.0 14.4 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -o injected.dylib -L/usr/local/lib -lobjc /var/folders/qh/dc0_lqxj2791lvymgc_gpctr0000gn/T/injected-8dca0c.o -lSystem /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "_NSHomeDirectory", referenced from:
      _try_decrypt_epub in injected-8dca0c.o
      _discoverEPUB in injected-8dca0c.o
  "_NSLog", referenced from:
      _get_sinf in injected-8dca0c.o
      _try_decrypt in injected-8dca0c.o
      _write_file in injected-8dca0c.o
      _write_file in injected-8dca0c.o
      _write_file in injected-8dca0c.o
      _make_base_epub_dir in injected-8dca0c.o
      _try_decrypt_epub in injected-8dca0c.o
      _try_decrypt_epub in injected-8dca0c.o
      _try_decrypt_epub in injected-8dca0c.o
      _try_decrypt_epub in injected-8dca0c.o
      _try_decrypt_epub in injected-8dca0c.o
      _try_decrypt_epub in injected-8dca0c.o
      _try_decrypt_epub in injected-8dca0c.o
      _try_decrypt_epub in injected-8dca0c.o
      ...
  "_OBJC_CLASS_$_NSConstantArray", referenced from:
       in injected-8dca0c.o
       in injected-8dca0c.o
  "_OBJC_CLASS_$_NSData", referenced from:
       in injected-8dca0c.o
  "_OBJC_CLASS_$_NSFileManager", referenced from:
       in injected-8dca0c.o
  "_OBJC_CLASS_$_NSString", referenced from:
       in injected-8dca0c.o
  "___CFConstantStringClassReference", referenced from:
       in injected-8dca0c.o
       in injected-8dca0c.o
       in injected-8dca0c.o
       in injected-8dca0c.o
       in injected-8dca0c.o
       in injected-8dca0c.o
       in injected-8dca0c.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


also it opens the tmp folder with the epub there, but its unreadable in Calibre.

**Comment by AngeloD2022** [comment]
> also it opens the tmp folder with the epub there, but its unreadable in Calibre.

Yeah it's not going to work until the binary is built for x86_64. At least, it _should_ work.

**Comment by AngeloD2022** [comment]
I'll try to look into this a bit more this weekend.

**Comment by Ardincani** [comment]
i messaged you on twitter if you want a more direct communication, either way, happy to help :)

**Comment by AngeloD2022** [comment]
I suppose this one warrants a PR for architecture checks in the build script.
