### ISSUE TITLE
Build warnings / Failed to extract itemName | Apple M1 Pro | macOS Sonoma 14.5

### ISSUE THREAD

**Issue by chrisdefazio** [ReverseApple/RemoveBooksDRM#7]
I get the following warnings when I run build.sh

`injected.m:152:11: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
    NSLog(baseDirectory);
          ^~~~~~~~~~~~~
injected.m:152:11: note: treat the string as an argument to avoid this
    NSLog(baseDirectory);
          ^
          @"%@",
injected.m:221:1: warning: non-void function does not return a value in all control paths [-Wreturn-type]
}`

When I run decrypt.sh I get:

`Failed to extract itemName from /Users/XXXXXX/Library/Containers/com.apple.BKAgentService/Data/Documents/iBooks/Books/XXXXX.epub`

Tried on:
- Apple M1 Pro | macOS Sonoma 14.5 | Books Version 6.4 (6070.12.11)
- Apple M2 | macOS Sonoma 14.5 | Books Version 6.4 (6070.12.11)

**Comment by AngeloD2022** [comment]
Hi, this should be fixed in #6. I haven't gotten to reviewing it yet, but feel free to try it.

**Comment by chrisdefazio** [comment]
That resolved my issue. Thanks!

**Comment by AngeloD2022** [comment]
Since it worked for you, I'm going to just merge it.
